## Q1. (40 points) Without using any third-party libraries or toolboxes, write code to
(a) take any three variable Boolean function as input

(b) generate training examples for this Boolean function

(c) train a neural network to learn this Boolean function, and

(d) verify that the function has been learned, for five separate Boolean functions.

In [31]:
import numpy as np
from numpy.random import rand as rand_uniform
import matplotlib.pyplot as plt

In [32]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def compute_gradient(inputs, predicted, actual):
    gradient = inputs * predicted * (predicted - actual) * (predicted - 1)
    return (np.sum(gradient, axis=0)).reshape((inputs.shape[1], 1))

def predicted_output(input_x, input_y, input_z, weights, bias):
    input_vector = np.array([[input_x, input_y, input_z]])
    prediction = sigmoid(np.dot(input_vector, weights) + bias)
    return int(prediction[0, 0] > 0.5)

def verify_bool_func(train_inputs, weights, bias):
    for test_input in train_inputs:
        test_x, test_y, test_z = test_input
        print(f"{test_input} -> [ {predicted_output(test_x, test_y, test_z, weights, bias)} ]")


In [33]:
def function_calling():
    train_inputs = np.array([[0, 0, 0],
                             [0, 0, 1],
                             [0, 1, 0],
                             [0, 1, 1],
                             [1, 0, 0],
                             [1, 0, 1],
                             [1, 1, 0],
                             [1, 1, 1]])

    train_outputs = np.zeros((8, 1))

    weights = rand_uniform(3, 1) - 0.5
    bias = rand_uniform(1, 1) - 0.5
    learning_rate = 1

    user_input = input("Use variables a, b, c as inputs.\nUse a' to indicate NOT of a.\nUse '+' for OR and '*' for AND operators.\nEx: a * b + c'\nEnter function: ")
    bool_func = ""

    for i in range(len(user_input)):
        if (user_input[i] == "'"):
            bool_func = bool_func[:-1] + "(1-" + str(bool_func[-1]) + ")"
        else:
            bool_func += user_input[i]

    print(f"Training on Boolean function ({user_input}) \n...")
    for i in range(8):
        a, b, c = train_inputs[i]
        train_outputs[i] = not(not(eval(bool_func)))

    epochs = []
    errors = []
    for epoch in range(1000):
        predictions = sigmoid(np.dot(train_inputs, weights) + bias).reshape(-1, 1)
        if (epoch % 100 == 0):
            mean_squared_error = np.sum((predictions - train_outputs) ** 2) / 8
            print(f"Epoch {epoch}, Error: {mean_squared_error}")
            epochs.append(epoch)
            errors.append(mean_squared_error)
    
        delta_weights = compute_gradient(train_inputs, predictions, train_outputs)
        delta_bias = compute_gradient(np.ones((8, 1)), predictions, train_outputs)

        weights += learning_rate * delta_weights
        bias += learning_rate * delta_bias

    print("Training Done\n")

    # plt.plot(epochs, errors, label='Error')
    # plt.xlabel('Epoch')
    # plt.ylabel('Mean Squared Error')
    # plt.title('Error vs Epoch')
    # plt.legend()
    # plt.show()

    print(f"\nVerifying the Boolean Function: {user_input}")
    print(f"[a b c] [{user_input}]")
    verify_bool_func(train_inputs, weights, bias)
    print("\n\n")

In [34]:
function_calling() # a + b + c

Training on Boolean function (a + b + c) 
...
Epoch 0, Error: 0.2798287156398136
Epoch 100, Error: 0.013614675029357887
Epoch 200, Error: 0.006205368339616828
Epoch 300, Error: 0.0038811907846688113
Epoch 400, Error: 0.0027876820743820826
Epoch 500, Error: 0.0021614125734151866
Epoch 600, Error: 0.0017586821608096574
Epoch 700, Error: 0.0014791682817477192
Epoch 800, Error: 0.0012744077485595997
Epoch 900, Error: 0.001118253820943749
Training Done


Verifying the Boolean Function: a + b + c
[a b c] [a + b + c]
[0 0 0] -> [ 0 ]
[0 0 1] -> [ 1 ]
[0 1 0] -> [ 1 ]
[0 1 1] -> [ 1 ]
[1 0 0] -> [ 1 ]
[1 0 1] -> [ 1 ]
[1 1 0] -> [ 1 ]
[1 1 1] -> [ 1 ]





In [35]:
function_calling() # a + b + c'

Training on Boolean function (a + b + c') 
...
Epoch 0, Error: 0.23934855088930806
Epoch 100, Error: 0.012176519345507118
Epoch 200, Error: 0.005766852659118112
Epoch 300, Error: 0.0036735021553456347
Epoch 400, Error: 0.002666333318603877
Epoch 500, Error: 0.0020814546355118276
Epoch 600, Error: 0.0017017641375083438
Epoch 700, Error: 0.0014364176653815705
Epoch 800, Error: 0.0012410096566552629
Epoch 900, Error: 0.00109136663502441
Training Done


Verifying the Boolean Function: a + b + c'
[a b c] [a + b + c']
[0 0 0] -> [ 1 ]
[0 0 1] -> [ 0 ]
[0 1 0] -> [ 1 ]
[0 1 1] -> [ 1 ]
[1 0 0] -> [ 1 ]
[1 0 1] -> [ 1 ]
[1 1 0] -> [ 1 ]
[1 1 1] -> [ 1 ]





In [36]:
function_calling() # a * b * c

Training on Boolean function (a * b * c) 
...
Epoch 0, Error: 0.3161304562312671
Epoch 100, Error: 0.03167419267299573
Epoch 200, Error: 0.017225758144176723
Epoch 300, Error: 0.01143760550700229
Epoch 400, Error: 0.00841776991359573
Epoch 500, Error: 0.006598454446795742
Epoch 600, Error: 0.0053958113245331125
Epoch 700, Error: 0.004547594239679974
Epoch 800, Error: 0.003920126903254938
Epoch 900, Error: 0.003438702575002671
Training Done


Verifying the Boolean Function: a * b * c
[a b c] [a * b * c]
[0 0 0] -> [ 0 ]
[0 0 1] -> [ 0 ]
[0 1 0] -> [ 0 ]
[0 1 1] -> [ 0 ]
[1 0 0] -> [ 0 ]
[1 0 1] -> [ 0 ]
[1 1 0] -> [ 0 ]
[1 1 1] -> [ 1 ]





In [37]:
function_calling() # a * b * c'

Training on Boolean function (a * b * c') 
...
Epoch 0, Error: 0.23800353114962194
Epoch 100, Error: 0.019230403044371062
Epoch 200, Error: 0.009626815643043223
Epoch 300, Error: 0.006210559519053703
Epoch 400, Error: 0.004521113600811864
Epoch 500, Error: 0.0035293531247543378
Epoch 600, Error: 0.0028825884796007334
Epoch 700, Error: 0.0024297939269292
Epoch 800, Error: 0.0020962025264089548
Epoch 900, Error: 0.0018408083152395937
Training Done


Verifying the Boolean Function: a * b * c'
[a b c] [a * b * c']
[0 0 0] -> [ 0 ]
[0 0 1] -> [ 0 ]
[0 1 0] -> [ 0 ]
[0 1 1] -> [ 0 ]
[1 0 0] -> [ 0 ]
[1 0 1] -> [ 0 ]
[1 1 0] -> [ 1 ]
[1 1 1] -> [ 0 ]





In [38]:
function_calling() # a * b + c

Training on Boolean function (a * b + c) 
...
Epoch 0, Error: 0.25356094837800197
Epoch 100, Error: 0.026172798384646888
Epoch 200, Error: 0.0143369080184499
Epoch 300, Error: 0.00958941847962622
Epoch 400, Error: 0.0071023764454781115
Epoch 500, Error: 0.00559620594144304
Epoch 600, Error: 0.004595533249566687
Epoch 700, Error: 0.003886567762725131
Epoch 800, Error: 0.0033600269848687624
Epoch 900, Error: 0.0029546344454664244
Training Done


Verifying the Boolean Function: a * b + c
[a b c] [a * b + c]
[0 0 0] -> [ 0 ]
[0 0 1] -> [ 1 ]
[0 1 0] -> [ 0 ]
[0 1 1] -> [ 1 ]
[1 0 0] -> [ 0 ]
[1 0 1] -> [ 1 ]
[1 1 0] -> [ 1 ]
[1 1 1] -> [ 1 ]





In [39]:
function_calling() # a' * b + c

Training on Boolean function (a' * b + c) 
...
Epoch 0, Error: 0.32739290863292153
Epoch 100, Error: 0.020746137653580767
Epoch 200, Error: 0.010829793103978039
Epoch 300, Error: 0.007120881816930371
Epoch 400, Error: 0.005237645921634788
Epoch 500, Error: 0.004114745111447068
Epoch 600, Error: 0.0033749908772568223
Epoch 700, Error: 0.0028534211012319725
Epoch 800, Error: 0.0024671652904771674
Epoch 900, Error: 0.0021702841695248175
Training Done


Verifying the Boolean Function: a' * b + c
[a b c] [a' * b + c]
[0 0 0] -> [ 0 ]
[0 0 1] -> [ 1 ]
[0 1 0] -> [ 1 ]
[0 1 1] -> [ 1 ]
[1 0 0] -> [ 0 ]
[1 0 1] -> [ 1 ]
[1 1 0] -> [ 0 ]
[1 1 1] -> [ 1 ]



